// <auto-generated />
using Euvic.StaffTraining.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Euvic.StaffTraining.Migrations.StaffTrainingReadonly
{
    [DbContext(typeof(StaffTrainingReadonlyContext))]
    partial class StaffTrainingReadonlyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Euvic.StaffTraining.Entities.Views.AttendeeSummary", b =>
                {
                    b.Property<long>("AttendeeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.ToView("dbo.AttendeeSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
